// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CategorySharesPermission string

const (
	CategorySharesPermissionRead  CategorySharesPermission = "read"
	CategorySharesPermissionWrite CategorySharesPermission = "write"
)

func (e *CategorySharesPermission) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategorySharesPermission(s)
	case string:
		*e = CategorySharesPermission(s)
	default:
		return fmt.Errorf("unsupported scan type for CategorySharesPermission: %T", src)
	}
	return nil
}

type NullCategorySharesPermission struct {
	CategorySharesPermission CategorySharesPermission `json:"category_shares_permission"`
	Valid                    bool                     `json:"valid"` // Valid is true if CategorySharesPermission is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategorySharesPermission) Scan(value interface{}) error {
	if value == nil {
		ns.CategorySharesPermission, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategorySharesPermission.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategorySharesPermission) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategorySharesPermission), nil
}

type Category struct {
	ID        uint64    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	OwnerID   uint64    `db:"owner_id" json:"owner_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type CategoryShare struct {
	ID               uint64                   `db:"id" json:"id"`
	CategoryID       uint64                   `db:"category_id" json:"category_id"`
	SharedWithUserID uint64                   `db:"shared_with_user_id" json:"shared_with_user_id"`
	Permission       CategorySharesPermission `db:"permission" json:"permission"`
	CreatedAt        time.Time                `db:"created_at" json:"created_at"`
}

type Todo struct {
	ID          uint64         `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	CategoryID  uint64         `db:"category_id" json:"category_id"`
	Completed   bool           `db:"completed" json:"completed"`
	UserID      uint64         `db:"user_id" json:"user_id"`
	CreatedBy   uint64         `db:"created_by" json:"created_by"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        uint64    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Email     string    `db:"email" json:"email"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
