// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"
	"database/sql"
)

const countAccessibleTodos = `-- name: CountAccessibleTodos :one
SELECT COUNT(DISTINCT t.id) as count
FROM todos t
INNER JOIN categories c ON t.category_id = c.id
LEFT JOIN category_shares cs ON c.id = cs.category_id AND cs.shared_with_user_id = ?
WHERE t.deleted_at IS NULL
AND (c.owner_id = ? OR cs.shared_with_user_id = ?)
`

type CountAccessibleTodosParams struct {
	SharedWithUserID   uint64 `db:"shared_with_user_id" json:"shared_with_user_id"`
	OwnerID            uint64 `db:"owner_id" json:"owner_id"`
	SharedWithUserID_2 uint64 `db:"shared_with_user_id_2" json:"shared_with_user_id_2"`
}

// Counts todos from categories owned by user OR shared with user
// Parameters: user_id, user_id, user_id
func (q *Queries) CountAccessibleTodos(ctx context.Context, arg CountAccessibleTodosParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessibleTodos, arg.SharedWithUserID, arg.OwnerID, arg.SharedWithUserID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosByCategoryID = `-- name: CountTodosByCategoryID :one
SELECT COUNT(*) as count FROM todos WHERE category_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountTodosByCategoryID(ctx context.Context, categoryID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosByCategoryID, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosByUserID = `-- name: CountTodosByUserID :one
SELECT COUNT(*) as count FROM todos WHERE user_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountTodosByUserID(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :execlastid
INSERT INTO todos (title, description, category_id, completed, user_id, created_by)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTodoParams struct {
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	CategoryID  uint64         `db:"category_id" json:"category_id"`
	Completed   bool           `db:"completed" json:"completed"`
	UserID      uint64         `db:"user_id" json:"user_id"`
	CreatedBy   uint64         `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.Completed,
		arg.UserID,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAccessibleTodosWithPagination = `-- name: GetAccessibleTodosWithPagination :many
SELECT DISTINCT t.id, t.title, t.description, t.category_id, t.completed, t.user_id, t.created_by, t.deleted_at, t.created_at, t.updated_at
FROM todos t
INNER JOIN categories c ON t.category_id = c.id
LEFT JOIN category_shares cs ON c.id = cs.category_id AND cs.shared_with_user_id = ?
WHERE t.deleted_at IS NULL
AND (c.owner_id = ? OR cs.shared_with_user_id = ?)
ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type GetAccessibleTodosWithPaginationParams struct {
	SharedWithUserID   uint64 `db:"shared_with_user_id" json:"shared_with_user_id"`
	OwnerID            uint64 `db:"owner_id" json:"owner_id"`
	SharedWithUserID_2 uint64 `db:"shared_with_user_id_2" json:"shared_with_user_id_2"`
	Limit              int32  `db:"limit" json:"limit"`
	Offset             int32  `db:"offset" json:"offset"`
}

// Gets todos from categories owned by user OR shared with user
// Parameters: user_id, user_id, user_id, limit, offset
func (q *Queries) GetAccessibleTodosWithPagination(ctx context.Context, arg GetAccessibleTodosWithPaginationParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAccessibleTodosWithPagination,
		arg.SharedWithUserID,
		arg.OwnerID,
		arg.SharedWithUserID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.Completed,
			&i.UserID,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, description, category_id, completed, user_id, created_by, deleted_at, created_at, updated_at
FROM todos
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetTodoByID(ctx context.Context, id uint64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.Completed,
		&i.UserID,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodosByCategoryID = `-- name: GetTodosByCategoryID :many
SELECT id, title, description, category_id, completed, user_id, created_by, deleted_at, created_at, updated_at
FROM todos
WHERE category_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetTodosByCategoryIDParams struct {
	CategoryID uint64 `db:"category_id" json:"category_id"`
	Limit      int32  `db:"limit" json:"limit"`
	Offset     int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetTodosByCategoryID(ctx context.Context, arg GetTodosByCategoryIDParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByCategoryID, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.Completed,
			&i.UserID,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByUserIDWithPagination = `-- name: GetTodosByUserIDWithPagination :many
SELECT id, title, description, category_id, completed, user_id, created_by, deleted_at, created_at, updated_at
FROM todos
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetTodosByUserIDWithPaginationParams struct {
	UserID uint64 `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetTodosByUserIDWithPagination(ctx context.Context, arg GetTodosByUserIDWithPaginationParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByUserIDWithPagination, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.Completed,
			&i.UserID,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET title = ?, description = ?, category_id = ?, completed = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTodoParams struct {
	Title       string         `db:"title" json:"title"`
	Description sql.NullString `db:"description" json:"description"`
	CategoryID  uint64         `db:"category_id" json:"category_id"`
	Completed   bool           `db:"completed" json:"completed"`
	ID          uint64         `db:"id" json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.Completed,
		arg.ID,
	)
	return err
}
